### ISSUE TITLE
Will v1.0 be uploaded to crates.io?

### ISSUE THREAD

**Issue by AHolliday** [PrototypeRailGun/binary_search_tree#1]
Crates.io has version 0.2.2 as the latest.  I was trying to use it in a project but there seems to be a bug in .remove().

**Comment by starovoid** [comment]
Please explain what the bug is.

**Comment by AHolliday** [comment]
Actually, it seems the bug was in the custom type I had created to add to
the BST.  Sorry about that.  I still wonder when 1.0 will be uploaded to
crates.io, though.
